'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { LuSparkles, LuArrowLeft } from 'react-icons/lu';

export default function TermsPage() {
  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: 'By accessing and using CreatorHub ("the Service"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to these terms, please do not use the Service.'
    },
    {
      title: '2. Use License',
      content: 'Permission is granted to temporarily access the Service for personal, non-commercial use. This is the grant of a license, not a transfer of title, and under this license you may not: modify or copy the materials; use the materials for any commercial purpose; attempt to decompile or reverse engineer any software contained on the Service; remove any copyright or other proprietary notations from the materials.'
    },
    {
      title: '3. User Accounts',
      content: 'When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms. You are responsible for safeguarding the password and for all activities that occur under your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.'
    },
    {
      title: '4. Content',
      content: 'Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, or other material ("Content"). You are responsible for the Content that you post to the Service, including its legality, reliability, and appropriateness. By posting Content, you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service.'
    },
    {
      title: '5. Intellectual Property',
      content: 'The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of CreatorHub and its licensors. The Service is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of CreatorHub.'
    },
    {
      title: '6. AI-Generated Content',
      content: 'Content generated by our AI tools is provided "as is" for your use. While we strive for accuracy and quality, AI-generated content should be reviewed and edited by you before publication. You retain all rights to content you create using our AI tools, subject to our general license to provide the service.'
    },
    {
      title: '7. Subscriptions',
      content: 'Some parts of the Service are billed on a subscription basis. You will be billed in advance on a recurring and periodic basis. Billing cycles are set on a monthly or annual basis. At the end of each billing cycle, your subscription will automatically renew unless you cancel it or we cancel it. You may cancel your subscription renewal through your account settings or by contacting us.'
    },
    {
      title: '8. Fee Changes',
      content: 'CreatorHub, in its sole discretion and at any time, may modify the subscription fees. Any subscription fee change will become effective at the end of the then-current billing cycle. We will provide you with reasonable prior notice of any change in subscription fees to give you an opportunity to cancel your subscription before such change becomes effective.'
    },
    {
      title: '9. Refunds',
      content: 'Except when required by law, paid subscription fees are non-refundable. Certain refund requests may be considered by CreatorHub on a case-by-case basis and granted at the sole discretion of CreatorHub.'
    },
    {
      title: '10. Prohibited Uses',
      content: 'You may not use the Service: (a) for any unlawful purpose or to solicit others to perform unlawful acts; (b) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (c) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (d) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate; (e) to submit false or misleading information; (f) to upload or transmit viruses or any other type of malicious code.'
    },
    {
      title: '11. Termination',
      content: 'We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service or contact us to delete your account.'
    },
    {
      title: '12. Limitation of Liability',
      content: 'In no event shall CreatorHub, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.'
    },
    {
      title: '13. Disclaimer',
      content: 'Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.'
    },
    {
      title: '14. Governing Law',
      content: 'These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which CreatorHub operates, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.'
    },
    {
      title: '15. Changes to Terms',
      content: 'We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.'
    },
    {
      title: '16. Contact Us',
      content: 'If you have any questions about these Terms, please contact us at legal@creatorhub.com or through our website contact form.'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-900 dark:to-purple-900">
      {/* Navigation */}
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div className="flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <motion.div 
              whileHover={{ rotate: 180, scale: 1.1 }}
              className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center shadow-lg"
            >
              <LuSparkles className="w-6 h-6 text-white" />
            </motion.div>
            <span className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
              CreatorHub
            </span>
          </Link>
          <Link href="/">
            <motion.button 
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="flex items-center gap-2 px-4 py-2 text-gray-600 dark:text-gray-300 hover:text-purple-600 transition-colors"
            >
              <LuArrowLeft className="w-4 h-4" />
              Back to Home
            </motion.button>
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 pb-20">
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          className="mb-12"
        >
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            <span className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
              Terms of Service
            </span>
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-400">
            Last Updated: November 24, 2024
          </p>
        </motion.div>

        <div className="space-y-8">
          {sections.map((section, index) => (
            <motion.div
              key={index}
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ delay: index * 0.05 }}
              className="bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-lg"
            >
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                {section.title}
              </h2>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                {section.content}
              </p>
            </motion.div>
          ))}
        </div>

        {/* Legal Navigation */}
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.8 }}
          className="mt-12 p-6 bg-gray-100 dark:bg-gray-800 rounded-xl"
        >
          <h3 className="font-bold text-gray-900 dark:text-white mb-4">
            More Legal Information
          </h3>
          <div className="flex flex-wrap gap-4">
            <Link href="/legal/privacy" className="text-purple-600 dark:text-purple-400 hover:underline">
              Privacy Policy
            </Link>
            <Link href="/legal/cookies" className="text-purple-600 dark:text-purple-400 hover:underline">
              Cookie Policy
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
